# Generated by Django 6.0.7 on 2026-07-16 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_designerapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_cm', models.DecimalField(decimal_places=1, max_digits=5)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('body_shape', models.CharField(blank=True, choices=[('hourglass', 'Hourglass'), ('pear', 'Pear / Triangle'), ('apple', 'Apple / Round'), ('rectangle', 'Rectangle / Straight'), ('inverted_triangle', 'Inverted Triangle')], default='', max_length=20)),
                ('measurements', models.JSONField(blank=True, default=dict)),
                ('reference_image', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='body_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
