# Generated by Django 6.0.7 on 2026-07-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_info',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
