# Generated by Django 6.0.7 on 2026-07-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(default='NGN', max_length=3),
        ),
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='fit_type',
            field=models.CharField(choices=[('slim', 'Slim'), ('regular', 'Regular'), ('oversized', 'Oversized')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, choices=[('ankara', 'Ankara'), ('lace', 'Lace'), ('silk', 'Silk'), ('cotton', 'Cotton'), ('denim', 'Denim'), ('linen', 'Linen'), ('velvet', 'Velvet'), ('chiffon', 'Chiffon')], max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='returns',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='ships_from',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='ships_within',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.JSONField(default=list),
        ),
    ]
