# Generated by Django 6.0.7 on 2026-07-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_currency_product_featured_product_fit_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='moderation_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
