# Generated by Django 6.0.7 on 2026-07-17 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('auth', 'Auth'), ('studio', 'Studio / Try-On'), ('marketplace', 'Marketplace'), ('orders', 'Orders / Checkout'), ('wardrobe', 'Wardrobe'), ('ai', 'AI Feature'), ('admin', 'Admin'), ('payment', 'Payment'), ('other', 'Other')], db_index=True, max_length=32)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('session_key', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_event',
                'indexes': [models.Index(fields=['category', 'created_at'], name='analytics_e_categor_e8aea1_idx'), models.Index(fields=['name', 'created_at'], name='analytics_e_name_6ca12c_idx')],
            },
        ),
    ]
